/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemreservasihotel;

import java.awt.CardLayout;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.JOptionPane;
import java.sql.Connection;
import sistemreservasihotel.dialog.GuestsDataMasterDialog;
import sistemreservasihotel.helper.DatabaseConnection;
import java.sql.PreparedStatement;
import java.util.Arrays;
import java.util.List;
import javax.swing.JTextField;
import sistemreservasihotel.model.User;

/**
 *
 * @author fdn-user
 */
public class DashboardFrame extends javax.swing.JFrame {
    
    private final User userLoggedIn;

    /**
     * Creates new form DashboardFrame
     * @param user
     */
    public DashboardFrame(User user) {
        this.userLoggedIn = user;
        initComponents();
        initUserData();
        initUIGuest();
    }
    
    private void initUserData() {
        tvUserInfo.setText("Hai, " + userLoggedIn.getUsername());
    }
    
    private void initUIGuest() {
        tvGuestName.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tvGuestName.getText().equals("Masukan Nama Tamu")) {
                    tvGuestName.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (tvGuestName.getText().isEmpty()) {
                    tvGuestName.setText("Masukan Nama Tamu");
                }
            }
        });
        
        tvGuestEmail.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tvGuestEmail.getText().equals("Masukan Email")) {
                    tvGuestEmail.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (tvGuestEmail.getText().isEmpty()) {
                    tvGuestEmail.setText("Masukan Email");
                }
            }
        });
        
        tvGuestPhone.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tvGuestPhone.getText().equals("Masukan Nomor Telepon")) {
                    tvGuestPhone.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (tvGuestPhone.getText().isEmpty()) {
                    tvGuestPhone.setText("Masukan Nomor Telepon");
                }
            }
        });
        
        tvGuestAddress.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tvGuestAddress.getText().equals("Masukan Alamat")) {
                    tvGuestAddress.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (tvGuestAddress.getText().isEmpty()) {
                    tvGuestAddress.setText("Masukan Alamat");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        menuPanel = new javax.swing.JPanel();
        btnCheckIn = new javax.swing.JButton();
        btnGuest = new javax.swing.JButton();
        btnReservationRoom1 = new javax.swing.JButton();
        btnCheckOut = new javax.swing.JButton();
        btnAdditionalService = new javax.swing.JButton();
        btnPayment1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tvUserInfo = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        regisPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tvGuestPhone = new javax.swing.JTextField();
        tvGuestName = new javax.swing.JTextField();
        tvGuestAddress = new javax.swing.JTextField();
        tvGuestEmail = new javax.swing.JTextField();
        btnShowGuests = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        reservePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        checkInPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(153, 153, 255));

        btnCheckIn.setBackground(new java.awt.Color(204, 204, 255));
        btnCheckIn.setText("Check In");
        btnCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInActionPerformed(evt);
            }
        });

        btnGuest.setBackground(new java.awt.Color(204, 204, 255));
        btnGuest.setText("Registrasi Tamu");
        btnGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestActionPerformed(evt);
            }
        });

        btnReservationRoom1.setBackground(new java.awt.Color(204, 204, 255));
        btnReservationRoom1.setText("Reservasi Kamar");
        btnReservationRoom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservationRoom1ActionPerformed(evt);
            }
        });

        btnCheckOut.setBackground(new java.awt.Color(204, 204, 255));
        btnCheckOut.setText("Check OUt");
        btnCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOutActionPerformed(evt);
            }
        });

        btnAdditionalService.setBackground(new java.awt.Color(204, 204, 255));
        btnAdditionalService.setText("Service Tambahan");
        btnAdditionalService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditionalServiceActionPerformed(evt);
            }
        });

        btnPayment1.setBackground(new java.awt.Color(204, 204, 255));
        btnPayment1.setText("Pembayaran");
        btnPayment1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayment1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("SELEMAT DATANG");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("DI RESERVASI HOTEL !");

        tvUserInfo.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        tvUserInfo.setText("label name");

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCheckOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdditionalService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPayment1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReservationRoom1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGuest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(tvUserInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tvUserInfo)
                .addGap(44, 44, 44)
                .addComponent(btnGuest, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReservationRoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckIn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPayment1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAdditionalService, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        regisPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Registrasi Data Tamu");

        tvGuestPhone.setText("Masukan Nomor Telepon");
        tvGuestPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvGuestPhoneActionPerformed(evt);
            }
        });

        tvGuestName.setText("Masukan Nama Tamu");
        tvGuestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvGuestNameActionPerformed(evt);
            }
        });

        tvGuestAddress.setText("Masukan Alamat");
        tvGuestAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvGuestAddressActionPerformed(evt);
            }
        });

        tvGuestEmail.setText("Masukan Email");
        tvGuestEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvGuestEmailActionPerformed(evt);
            }
        });

        btnShowGuests.setText("Lihat Data Tamu");
        btnShowGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowGuestsActionPerformed(evt);
            }
        });

        btnSave.setText("Simpan");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout regisPanelLayout = new javax.swing.GroupLayout(regisPanel);
        regisPanel.setLayout(regisPanelLayout);
        regisPanelLayout.setHorizontalGroup(
            regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisPanelLayout.createSequentialGroup()
                .addGap(326, 326, 326)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regisPanelLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addGroup(regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regisPanelLayout.createSequentialGroup()
                        .addGroup(regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tvGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvGuestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tvGuestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regisPanelLayout.createSequentialGroup()
                        .addComponent(btnShowGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198))))
            .addGroup(regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(regisPanelLayout.createSequentialGroup()
                    .addGap(216, 216, 216)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(443, Short.MAX_VALUE)))
        );
        regisPanelLayout.setVerticalGroup(
            regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regisPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(60, 60, 60)
                .addComponent(tvGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tvGuestAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tvGuestPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tvGuestEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnShowGuests, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(regisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, regisPanelLayout.createSequentialGroup()
                    .addContainerGap(421, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(157, 157, 157)))
        );

        mainPanel.add(regisPanel, "regisPanel");

        jLabel2.setText("2");

        javax.swing.GroupLayout reservePanelLayout = new javax.swing.GroupLayout(reservePanel);
        reservePanel.setLayout(reservePanelLayout);
        reservePanelLayout.setHorizontalGroup(
            reservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservePanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel2)
                .addContainerGap(563, Short.MAX_VALUE))
        );
        reservePanelLayout.setVerticalGroup(
            reservePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(reservePanelLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(jLabel2)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        mainPanel.add(reservePanel, "reservePanel");

        jLabel3.setText("3");

        javax.swing.GroupLayout checkInPanelLayout = new javax.swing.GroupLayout(checkInPanel);
        checkInPanel.setLayout(checkInPanelLayout);
        checkInPanelLayout.setHorizontalGroup(
            checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, checkInPanelLayout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(331, 331, 331))
        );
        checkInPanelLayout.setVerticalGroup(
            checkInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkInPanelLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jLabel3)
                .addContainerGap(421, Short.MAX_VALUE))
        );

        mainPanel.add(checkInPanel, "checkInPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInActionPerformed

        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "checkInPanel");
    }//GEN-LAST:event_btnCheckInActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "regisPanel");
    }//GEN-LAST:event_btnGuestActionPerformed

    private void btnReservationRoom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservationRoom1ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "reservePanel");
    }//GEN-LAST:event_btnReservationRoom1ActionPerformed

    private void btnCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCheckOutActionPerformed

    private void btnAdditionalServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditionalServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdditionalServiceActionPerformed

    private void btnPayment1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayment1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayment1ActionPerformed

    private void tvGuestPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvGuestPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvGuestPhoneActionPerformed

    private void tvGuestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvGuestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvGuestNameActionPerformed

    private void tvGuestAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvGuestAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvGuestAddressActionPerformed

    private void tvGuestEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvGuestEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvGuestEmailActionPerformed

    private void btnShowGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowGuestsActionPerformed
        // TODO add your handling code here:
        GuestsDataMasterDialog dialog = new GuestsDataMasterDialog(this, true);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnShowGuestsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        saveGuest();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdditionalService;
    private javax.swing.JButton btnCheckIn;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnPayment1;
    private javax.swing.JButton btnReservationRoom1;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowGuests;
    private javax.swing.JPanel checkInPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel regisPanel;
    private javax.swing.JPanel reservePanel;
    private javax.swing.JTextField tvGuestAddress;
    private javax.swing.JTextField tvGuestEmail;
    private javax.swing.JTextField tvGuestName;
    private javax.swing.JTextField tvGuestPhone;
    private javax.swing.JLabel tvUserInfo;
    // End of variables declaration//GEN-END:variables

private void saveGuest() {
    String name = tvGuestName.getText().trim();
    String address = tvGuestAddress.getText().trim();
    String phone = tvGuestPhone.getText().trim();
    String email = tvGuestEmail.getText().trim();
    
    if (name.isEmpty() || phone.isEmpty() || email.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama, No HP, dan Email wajib diisi.");
            return;
    }
    
    try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "INSERT INTO guests (name, address, phone_number, email) VALUES (?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, name);
            stmt.setString(2, address);
            stmt.setString(3, phone);
            stmt.setString(4, email);

            int rowsInserted = stmt.executeUpdate();
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Tamu berhasil terdaftar!");
                resetField(Arrays.asList(tvGuestName, tvGuestAddress, tvGuestPhone, tvGuestEmail));
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data tamu.");
        }
    }

private void resetField(List<JTextField> fields) {
    for (JTextField field : fields) {
        field.setText("");
    }
}


}