/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sistemreservasihotel;

import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import sistemreservasihotel.helper.service.AuthService;
import sistemreservasihotel.model.User;

/**
 *
 * @author fdn-user
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
        initUI();
        jPanel1.requestFocus();
    }
    
    private void initUI() {
        tvUsername.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (tvUsername.getText().equals("Masukkan username")) {
                    tvUsername.setText("");
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (tvUsername.getText().isEmpty()) {
                    tvUsername.setText("Masukkan username");
                }
            }
        });
        tvPasswordUser.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                String pass = new String(tvPasswordUser.getPassword());
                if (pass.equals("Masukkan password")) {
                    tvPasswordUser.setText("");
                    tvPasswordUser.setEchoChar('\u2022'); // Atur ulang jadi titik (atau '*')
                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                String pass = new String(tvPasswordUser.getPassword());
                if (pass.isEmpty()) {
                    tvPasswordUser.setText("Masukkan password");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tvUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        tvTitleWelcome = new javax.swing.JLabel();
        tvPasswordUser = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setText("Enter your username and password to log in.");

        tvUsername.setText("Masukkan username");
        tvUsername.setSize(new java.awt.Dimension(78, 24));
        tvUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvUsernameActionPerformed(evt);
            }
        });
        tvUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvUsernameKeyPressed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(153, 204, 255));
        btnLogin.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        tvTitleWelcome.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        tvTitleWelcome.setText("Welcome To Reservation Dimas' Hotel");

        tvPasswordUser.setText("Masukkan password");
        tvPasswordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvPasswordUserActionPerformed(evt);
            }
        });
        tvPasswordUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tvPasswordUserKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Log in to your account");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tvPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tvTitleWelcome))
                .addGap(145, 145, 145))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(tvTitleWelcome)
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(tvUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tvPasswordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tvUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvUsernameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tvUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = tvUsername.getText();
        String password = new String(tvPasswordUser.getPassword());

        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan Password wajib diisi!");
            return;
        }

        User user = AuthService.login(username, password);

          if (user != null) {
              JOptionPane.showMessageDialog(this, "Login berhasil sebagai " + user.getRole());

              new DashboardFrame(user).setVisible(true);

              this.dispose(); // tutup form login
          } else {
              JOptionPane.showMessageDialog(this, "Username atau password salah.");
          }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void tvPasswordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvPasswordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvPasswordUserActionPerformed

    private void tvUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvUsernameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tvPasswordUser.requestFocus();
        }
    }//GEN-LAST:event_tvUsernameKeyPressed

    private void tvPasswordUserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tvPasswordUserKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.requestFocus();
        }
    }//GEN-LAST:event_tvPasswordUserKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginForm().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tvPasswordUser;
    private javax.swing.JLabel tvTitleWelcome;
    private javax.swing.JTextField tvUsername;
    // End of variables declaration//GEN-END:variables
}
